version: 2
   jobs:	
    build:
      docker: 
        - image: circleci/php:7.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command

