version: 2
   jobs:
    build:
      docker: 
        - image: circleci/php:7.2 # the primary container, where your job's commands are run
      steps:
 	 - checkout
        - run:
		  name: The First Step
		  command: |
		    echo 'Hello World!'
		    echo 'This is the delivery pipeline'
